# numpy = numerical python

In [1]:
import numpy as np

# array = o lista cu toate elemente de acelasi tip

In [2]:
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [3]:
arr = np.array([0, 1, 2, 3, 4])
type(arr), arr.dtype

(numpy.ndarray, dtype('int64'))

In [4]:
arr = np.array([0, 1, 2, 3.0, 4])
type(arr), arr.dtype, 

(numpy.ndarray, dtype('float64'))

In [5]:
arr = np.arange(10)
arr, type(arr), arr.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray, dtype('int64'))

In [6]:
arr = np.arange(10, 20)
arr, type(arr), arr.dtype

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 numpy.ndarray,
 dtype('int64'))

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(10) * 2


array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [14]:
print([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.] * 2)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [15]:
print([1., 1.] * 2)

[1.0, 1.0, 1.0, 1.0]


In [16]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [17]:
np.array([1, 2, 3]) ** 2

array([1, 4, 9])

In [18]:
np.arange(100)  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
np.arange(100) % 7  

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1])

In [20]:
np.arange(100) % 7  == 0

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False])

In [ ]:
np.arange(100) [   np.arange(100) % 7  == 0  ]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [23]:
np.arange(100).reshape((10, 10))


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
np.arange(100).reshape((4, 25))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
np.random.randint(1, 100, 3)

array([41, 29, 75])

In [27]:
np.random.randint(1, 100, 3)

array([ 3, 56, 63])

In [28]:
np.random.randint(1, 100, (3, 3))

array([[ 5, 74,  8],
       [76, 14, 46],
       [23, 49, 62]])

In [30]:
np.random.random(3)

array([0.4335112 , 0.84896207, 0.15597423])

In [31]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [32]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [33]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
array = np.random.randint(21, 25, 50)
array

array([23, 22, 23, 23, 24, 22, 22, 23, 21, 24, 22, 24, 24, 24, 22, 21, 23,
       21, 23, 23, 24, 21, 22, 24, 22, 24, 23, 24, 23, 23, 22, 22, 22, 23,
       24, 22, 23, 24, 24, 22, 23, 21, 21, 23, 22, 21, 22, 22, 21, 23])

In [36]:
array [ array == 22]

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [41]:
array = np.random.randint(2, 10000, 50)
array

array([ 676,  149, 1101, 1696,  851,   60, 8251,  119, 6362, 6842,  640,
       6436, 9211, 5272, 8783, 5962,  447, 3310, 6158, 7860, 8124, 3688,
       7781,  383, 7523, 6056,  183, 1582, 5092,  145, 8828, 1061, 3597,
       8260, 6217, 2508, 6482, 4575, 6892, 5848, 5564, 6566, 5009, 5604,
       7361, 8666, 2406, 3573, 6381,  956])

In [40]:
array.max(), array.argmax()

(np.int64(9211), np.int64(12))